version: '3.8'
services:

  postgres:
    image: postgres:13.5
    container_name: clients_database
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - '5433:5432'

    volumes:
      - ./postgres:/var/lib/postgresql/data
